main: main.java.water.of.cup.cameras.Camera
name: Minecraft-Camera
version: '2.4'
description: Take Pictures.
author: Nicholas Kopiwoda
api-version: "1.21"
softdepend: [Multiverse-Core]
commands:
  takepicture:
    description: Take a picture
  copypicture:
    description: Copy a picture to clipboard
  tagpicture:
    description: Tag a picture
  fetchpicture:
    description: Fetch a picture by it's tag
  migratepictures:
    description: Migrate pictures (should only be used if you are upgrading from versions below 1.18)